POST http://localhost:3333/courses
Content-Type: application/json

{
    "title": "Curso de Fastify"
}

###

GET http://localhost:3333/courses


###

GET http://localhost:3333/courses/964f5a7b-5cbe-4c49-aefc-0f970af78457
